In [1]:
import sys
import os

sys.path.append(os.path.abspath('..'))

from src.utils.gtfs_parser import build_gtfs_dataset
from src.core.config import Config

df = build_gtfs_dataset(Config.GTFS_DATA_DIR, Config.GTFS_DATA_DIR)

print(df.shape)
display(df.head())

2026-09-30 15:43:13Z | WARNING  | gtfs_parser | 1 viagens representativas com duração programada <= 0 min ignoradas (NaN)
2026-09-30 15:43:19Z | INFO     | gtfs_parser | Dataset saved successfully at: c:\Users\pedro\OneDrive\Documentos\Unifei\Topicos\sptrans-rain-impact\data\bronze\gtfs\routes_geometry.geojson

(2239, 27)

,shape_id,route_id,route_short_name,route_long_name,direction_id,trip_headsign,geometry,length_km,weekday_trips,saturday_trips,...,origin_lat,origin_lon,dest_stop_id,dest_stop_name,dest_lat,dest_lon,n_stops,scheduled_duration_min,scheduled_speed_kmh,scheduled_speed_suspect
0,44331,4113-10,4113-10,Gentil De Moura - Pça. Da República,0,Pça. Da República,"LINESTRING (-46.61285 -23.60143, -46.61275 -23...",20.87,166,166,...,-23.602308,-46.612888,3305204,"R. Visc. De Pirajá, 462",-23.602308,-46.612888,72,146.0,8.58,False
1,45025,4112-10,4112-10,Sta. Margarida Maria - Pça. Da República,0,Pça. Da República,"LINESTRING (-46.6261 -23.58108, -46.62615 -23....",12.87,66,0,...,-23.581210,-46.626147,920016070,"Av. Lacerda Franco, 2080",-23.580877,-46.626091,41,103.0,7.50,False
2,45866,273R-10,273R-10,Jd. Robru - Metrô Artur Alvim,0,Metrô Artur Alvim,"LINESTRING (-46.41254 -23.52208, -46.41252 -23...",14.21,88,88,...,-23.521998,-46.412425,50007001,Terminal Metrô Artur Alvim,-23.540408,-46.483155,50,68.0,12.54,False
3,47323,372U-10,372U-10,Vl. Sta. Isabel - Metrô Tatuapé,0,Metrô Tatuapé,"LINESTRING (-46.53737 -23.55645, -46.53749 -23...",10.56,207,207,...,-23.556408,-46.537463,8210188,Terminal Metrô Tatuapé (lado Sul- Shop. Tatuapé),-23.540973,-46.576459,36,62.0,10.22,False
4,48595,6L07-10,6L07-10,Jd. Sta. Fé - Term. Varginha,0,Term. Varginha,"LINESTRING (-46.71186 -23.83136, -46.71169 -23...",9.80,37,37,...,-23.831368,-46.711769,560009247,Terminal Varginha,-23.766702,-46.716302,31,42.0,14.00,False

In [2]:
import pandas as pd
from src.utils.station_parser import get_sp_stations

stations_list = get_sp_stations(Config.STATIONS_DATA_DIR)

df_stations = pd.DataFrame(stations_list)

print(f"Shape: {df_stations.shape}")
display(df_stations.head())

Cemaden Token acquired.
Total active/mapped stations: 79
Saved to: C:\Users\pedro\OneDrive\Documentos\Unifei\Topicos\sptrans-rain-impact\data\bronze\stations\cemaden_sp_stations.json
Shape: (79, 11)

,station_name,city,state,latitude,longitude,status,installation_date,last_update,station_id,station_type,source
0,Jardim Eledy,SÃO PAULO,SP,-23.64900,-46.78600,Offline,2013-11-14,2024-06-04,355030899A,Pluviométrica,CEMADEN
1,Jardim Romano,SÃO PAULO,SP,-23.47888,-46.38121,Active,2014-12-02,2026-09-30,355030898A,Pluviométrica,CEMADEN
2,Jaguaré,SÃO PAULO,SP,-23.55000,-46.74300,Active,2013-11-08,2026-09-30,355030897A,Pluviométrica,CEMADEN
3,Jardim João XXIII,SÃO PAULO,SP,-23.60000,-46.78900,Active,2013-11-12,2026-09-30,355030896A,Pluviométrica,CEMADEN
4,Pirajussara,SÃO PAULO,SP,-23.63800,-46.78000,Active,2013-11-07,2026-09-30,355030895A,Pluviométrica,CEMADEN